### ISSUE TITLE
Mp3 playback fails with error 984

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit-mp3#1]
This program  in the v2 editor fails when touch sensors are touched:

https://makecode.microbit.org/_KTP1eWXqmRpc

but in v1, the program works:

https://makecode.microbit.org/#v1/_Jk56y498rcJ1

**Comment by HyperDuino** [comment]
Here is another example using on-touch events that fails in v2 of the editor:

https://makecode.microbit.org/_cKg51JXvpWE8

but works in v1:

https://makecode.microbit.org/#v1/_aAL55ML6wh0K

**Comment by MKleinSB** [comment]
Same on my Calliope Mini. But it even fails when I use normal button-events and click 60 to 80 times to play a mp3-file

**Comment by philipphenkel** [comment]
Fixed with 07d26de33dfa71b43fa0371423e0ca24a0c21f6b, we are now using https://github.com/philipphenkel/pxt-serial-read to read from the serial port.
